version: '3'

services:
  app:
    container_name: PixPayView-API
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: YOUR-SECRET
      JWT_EXPIRATION: 3600
      PAYMENT_QRCODE_EXPIRES: 30
    depends_on:
      - postgresql

  postgresql:
    container_name: PixPayView-DB
    image: postgres
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "5432:5432"