version: '3'

services:
  app:
    container_name: PixPayView-API
    build: .
    ports:
      - "80:80"
    environment:
      SERVER_PORT: 80
      SPRING_DATASOURCE_HOSTNAME: postgresql
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: YOUR-SECRET
      JWT_EXPIRATION: 3600
      PAYMENT_QRCODE_EXPIRES: 30
    networks:
      - pixpayview-net
    depends_on:
      - postgresql

  postgresql:
    container_name: PixPayView-DB
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: pixpayview
      POSTGRES_PASSWORD: password
    networks:
      - pixpayview-net
    ports:
      - "5432:5432"

networks:
  pixpayview-net:
    driver: bridge